### ISSUE TITLE
Installation trouble

### ISSUE THREAD

**Issue by frankdugan3** [valiot/opex62541#11]
I'm having a similar issue to #10, but I'm using Manjaro rather than Ubuntu 20.04. After adding the missing symlinks like the OP, I'm able to compile. Once I do get it compiled, however, even a simple attempt to start a client:
```elixir
{:ok, client_pid} = OpcUA.Client.start_link()
IO.inspect(OpcUA.Client.get_state(client_pid))
```
Fails to respond and times out after the default 5000ms. I'm thinking that perhaps the port isn't working correctly, perhaps due to my version of `mbedtls` being much newer than used in Ubuntu 18.04?

I noticed there is a pre-compiled version release. I would be happy to give that a spin, but I'm not sure how to go about using it. Are there any instructions available for using that?

**Comment by alde103** [comment]
The precompiled version only covers `open62451` (C source code), `opex62451` would still have to compile the wrapper, to use the precompiled version, you could use `export MANUAL_BUILD=false`; Is there any warning message during compilation time? Can you share your development environment?

**Comment by frankdugan3** [comment]
Sorry for a delayed response, had to set this aside while working on other things.

I'm new to C development, but after looking into it, I think the easiest path forward for my use case is to use `nix-shell` to provide a reproducible development environment and commit a `shell.nix` file to the project's repo. Once I have that sorted, I will post here what I came up with for anyone else that may find it useful and close this thread.

**Comment by frankdugan3** [comment]
OK, I've spent quite a bit of time trying to get a working environment, and I keep coming back to the same crash message.

```elixir
defmodule App.Test do
  alias OpcUA.Client

  def init() do
    {:ok, client_pid} = Client.start_link()
    IO.inspect(client_pid)
    :ok = Client.set_config(client_pid)
  end
end
```

Running it fails with this output:
```
iex(1)> recompile; App.Test.init()
Compiling 1 file (.ex)
#PID<0.1839.0>
iex(1)> opc_ua_client: Expecting ref
                                    [warn] (Elixir.OpcUA.Client) Error code: 1.
** (exit) exited in: GenServer.call(#PID<0.1839.0>, {:config, {:set_config, %{}}}, 5000)
    ** (EXIT) time out
    (elixir 1.12.2) lib/gen_server.ex:1024: GenServer.call/3
    (app 0.1.43) lib/test_opcua.ex:7: App.Test.init/0
iex(1)> [error] GenServer #PID<0.1839.0> terminating
** (stop) :restart
Last message: {#Port<0.50>, {:exit_status, 1}}
State: %OpcUA.Client.State{controlling_process: #PID<0.1721.0>, port: #Port<0.50>}
```

That seems to be coming from [common.c](https://github.com/valiot/opex62541/blob/992b472fea30bc606dd5f6f9e03c37b75e9ff7d1/src/common.c#L955).

I don't see any substantial build errors. Here's the build output:
```
==> opex62541
-- DOWNLOAD_BUILD
open62541-linux64/
open62541-linux64/include/
open62541-linux64/include/open62541.h
open62541-linux64/include/open62541.c
open62541-linux64/lib/
open62541-linux64/lib/libopen62541.so.1
open62541-linux64/lib/cmake/
open62541-linux64/lib/cmake/open62541/
open62541-linux64/lib/cmake/open62541/open62541Targets.cmake
open62541-linux64/lib/cmake/open62541/open62541ConfigVersion.cmake
open62541-linux64/lib/cmake/open62541/open62541Config.cmake
open62541-linux64/lib/cmake/open62541/open62541Macros.cmake
open62541-linux64/lib/cmake/open62541/open62541Targets-relwithdebinfo.cmake
open62541-linux64/lib/pkgconfig/
open62541-linux64/lib/pkgconfig/open62541.pc
open62541-linux64/lib/libopen62541.so.1.0.0
open62541-linux64/lib/libopen62541.so
-- Debugs CMAKE_C_FAGS=; BASE_C_FLAGS=-g -Wall -Wextra  -std=c99 -lpthread; MBEDTLS_FOLDER_LIBRARY= MBEDTLS_FOLDER_INCLUDE=
-- Configuring done
-- Generating done
-- Build files have been written to: /hsm/_build/dev/cmake/Opex62541

Scanning dependencies of target server_example
[  6%] Building C object CMakeFiles/server_example.dir/server_example.c.o
Elapsed time: 0 s. (time), 0.000371 s. (clock)
[ 12%] Building C object CMakeFiles/server_example.dir/erlcmd.c.o
Elapsed time: 0 s. (time), 0.000439 s. (clock)
[ 18%] Building C object CMakeFiles/server_example.dir/common.c.o
Elapsed time: 1 s. (time), 0.000401 s. (clock)
[ 25%] Linking C executable /hsm/_build/dev/lib/opex62541/priv/server_example
[ 25%] Built target server_example
Scanning dependencies of target client_example
[ 31%] Building C object CMakeFiles/client_example.dir/client_example.c.o
Elapsed time: 0 s. (time), 0.000421 s. (clock)
[ 37%] Building C object CMakeFiles/client_example.dir/erlcmd.c.o
Elapsed time: 0 s. (time), 0.000302 s. (clock)
[ 43%] Building C object CMakeFiles/client_example.dir/common.c.o
Elapsed time: 0 s. (time), 0.000385 s. (clock)
[ 50%] Linking C executable /hsm/_build/dev/lib/opex62541/priv/client_example
[ 50%] Built target client_example
Scanning dependencies of target opc_ua_server
[ 56%] Building C object CMakeFiles/opc_ua_server.dir/opc_ua_server.c.o
/hsm/deps/opex62541/src/opc_ua_server.c: In function ‘handle_add_namespace’:
/hsm/deps/opex62541/src/opc_ua_server.c:690:23: warning: initialization of ‘UA_Int16 *’ {aka ‘short int *’} from ‘UA_UInt16’ {aka ‘short unsigned int’} makes pointer from integer without a cast [-Wint-conversion]
     UA_Int16 *ns_id = UA_Server_addNamespace(server, namespace);
                       ^~~~~~~~~~~~~~~~~~~~~~
Elapsed time: 0 s. (time), 0.000385 s. (clock)
[ 62%] Building C object CMakeFiles/opc_ua_server.dir/erlcmd.c.o
Elapsed time: 0 s. (time), 0.000458 s. (clock)
[ 68%] Building C object CMakeFiles/opc_ua_server.dir/common.c.o
Elapsed time: 1 s. (time), 0.000424 s. (clock)
[ 75%] Linking C executable /hsm/_build/dev/lib/opex62541/priv/opc_ua_server
[ 75%] Built target opc_ua_server
Scanning dependencies of target opc_ua_client
[ 81%] Building C object CMakeFiles/opc_ua_client.dir/opc_ua_client.c.o
Elapsed time: 0 s. (time), 0.000403 s. (clock)
[ 87%] Building C object CMakeFiles/opc_ua_client.dir/erlcmd.c.o
Elapsed time: 0 s. (time), 0.00044 s. (clock)
[ 93%] Building C object CMakeFiles/opc_ua_client.dir/common.c.o
Elapsed time: 0 s. (time), 0.000489 s. (clock)
[100%] Linking C executable /hsm/_build/dev/lib/opex62541/priv/opc_ua_client
[100%] Built target opc_ua_client

Compiling 10 files (.ex)
Generated opex62541 app
```
Here's the development environment I'm using:
(start it with `docker run -it -P -e LOCAL_UID=$(id -u $USER) -e LOCAL_GID=$(id -g $USER) --mount type=bind,source="$(pwd)",target=/app app`)

It's part of a large phoenix app, so some of the stuff in there is not necessarily needed for Opex.
```elixir
# in mix.exs
{:opex62541, github: "valiot/opex62541"},
```
```Dockerfile
# Dockerfile
FROM elixir:1.12.2

###############################################################################
### INSTALL DEPS
###############################################################################
RUN apt-get update && apt-get install lsb-release --yes
RUN sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
RUN wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
RUN curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
# RUN apt-get update

### ELIXIR/PHOENIX DEPS
RUN apt-get install --yes build-essential inotify-tools git nodejs inotify-tools postgresql-12 postgresql-client-12 && \
  update-ca-certificates --fresh

### APP DEPS
# RUN apt-get install --yes graphviz restic samba-client

### OPEX62541 DEPS
RUN apt-get install --yes gcc pkg-config cmake python libmbedtls-dev
RUN ln -sf /usr/lib/x86_64-linux-gnu/libmbedcrypto.so /usr/lib/x86_64-linux-gnu/libmbedcrypto.so.1

USER postgres

RUN    /etc/init.d/postgresql start && \
  psql --command "ALTER ROLE postgres WITH PASSWORD 'postgres';" && \
  createdb app_dev

RUN echo "host all  all    0.0.0.0/0  md5" >> /etc/postgresql/12/main/pg_hba.conf

RUN echo "listen_addresses='*'" >> /etc/postgresql/12/main/postgresql.conf

# Add VOLUMEs to allow backup of config, logs and databases
VOLUME  ["/etc/postgresql", "/var/log/postgresql", "/var/lib/postgresql"]

# Set the default command to run when starting the container

###############################################################################
### SET ENVIRONMENT
###############################################################################

USER root
WORKDIR /app
EXPOSE 5000
# EXPOSE 5432
ENV HOME=/app

# CMD ["bash"]
CMD ["./run.sh"]
```

```sh
# run.sh
#!/bin/sh
set -e

su postgres -c '/usr/lib/postgresql/12/bin/postgres -D /var/lib/postgresql/12/main -c config_file=/etc/postgresql/12/main/postgresql.conf' &

export PS1='\n\[\033[1;32m\][docker:\w]($(git rev-parse --abbrev-ref HEAD))\$\[\033[0m\] '
export ERL_AFLAGS="-kernel shell_history enabled"

# Ensure the app's dependencies are installed
mix deps.get
mix ecto.migrate
# mix deps.clean opex62541 && mix deps.get && mix deps.compile opex62541
bash
```

**Comment by alde103** [comment]
It seems `opex62541` is not compatible with `elixir 1.12.2` (OTP24), try using `FROM elixir:1.11.4-slim` in your dockerfile, it works for me.

**Comment by frankdugan3** [comment]
Unfortunately, way too many of my app's deps can't downgrade below OTP 24, so I wasn't able to verify that. Now that I have a baseline for last working version, I'll check the OTP/Elixir changelogs since then and see where the trouble might be.

**Comment by frankdugan3** [comment]
Update: I changed the Dockerfile to build from Ubuntu 18.04 and manually installed Erlang/Elixir, same issue. So it does indeed seem to be OTP 24/Elixir 1.12 that is at issue, but these seem to have pretty minor changes so I'm not sure what's the issue here. Will keep digging.

**Comment by alde103** [comment]
It seems that in elixir 1.12.2 (OTP24), there has been a change in the `handle_call` callback arguments, specifically in the argument `from`;  this is a big breaking change to `opex62541`, because of the way the `c middleware`  expects a certain type of data. For example:
In Elixir 1.11.4 (OTP23):
{:set_client_config, {#PID<0.234.0>, #Reference<0.4179689082.2582118402.232227>}, %{}}

In Elixir 1.12.2 (OTP24):
{:set_client_config, {#PID<0.1389.0>, [:alias | #Reference<0.1463171519.705232897.9352>]}, %{}}

The C code is not prepared for this structure, I am looking (and open) for scalable ways to handle both.
